import "./globals.css";
import { Header } from "@/components/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="h-full" lang="en">
      <body className="flex flex-col h-full">
        <Header />

        <div className="flex-1 max-w-6xl m-auto py-12 w-full">{children}</div>
      </body>
    </html>
  );
}
